//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18010
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoombuM1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ZoombuM1Service.DAL.entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.User[] FollowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.Group[] GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.Post[] PostsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.User[] Follow {
            get {
                return this.FollowField;
            }
            set {
                if ((object.ReferenceEquals(this.FollowField, value) != true)) {
                    this.FollowField = value;
                    this.RaisePropertyChanged("Follow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.Group[] Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.Post[] Posts {
            get {
                return this.PostsField;
            }
            set {
                if ((object.ReferenceEquals(this.PostsField, value) != true)) {
                    this.PostsField = value;
                    this.RaisePropertyChanged("Posts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/ZoombuM1Service.DAL.entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.Post[] PostsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserOwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.Post[] Posts {
            get {
                return this.PostsField;
            }
            set {
                if ((object.ReferenceEquals(this.PostsField, value) != true)) {
                    this.PostsField = value;
                    this.RaisePropertyChanged("Posts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserOwnerId {
            get {
                return this.UserOwnerIdField;
            }
            set {
                if ((this.UserOwnerIdField.Equals(value) != true)) {
                    this.UserOwnerIdField = value;
                    this.RaisePropertyChanged("UserOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/ZoombuM1Service.DAL.entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.Comment[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.Like[] LikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.Comment[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfCreation {
            get {
                return this.DateOfCreationField;
            }
            set {
                if ((this.DateOfCreationField.Equals(value) != true)) {
                    this.DateOfCreationField = value;
                    this.RaisePropertyChanged("DateOfCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.Like[] Likes {
            get {
                return this.LikesField;
            }
            set {
                if ((object.ReferenceEquals(this.LikesField, value) != true)) {
                    this.LikesField = value;
                    this.RaisePropertyChanged("Likes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/ZoombuM1Service.DAL.entities")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commentaire {
            get {
                return this.CommentaireField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentaireField, value) != true)) {
                    this.CommentaireField = value;
                    this.RaisePropertyChanged("Commentaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfCreation {
            get {
                return this.DateOfCreationField;
            }
            set {
                if ((this.DateOfCreationField.Equals(value) != true)) {
                    this.DateOfCreationField = value;
                    this.RaisePropertyChanged("DateOfCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostId {
            get {
                return this.PostIdField;
            }
            set {
                if ((this.PostIdField.Equals(value) != true)) {
                    this.PostIdField = value;
                    this.RaisePropertyChanged("PostId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Like", Namespace="http://schemas.datacontract.org/2004/07/ZoombuM1Service.DAL.entities")]
    [System.SerializableAttribute()]
    public partial class Like : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZoombuM1.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostId {
            get {
                return this.PostIdField;
            }
            set {
                if ((this.PostIdField.Equals(value) != true)) {
                    this.PostIdField = value;
                    this.RaisePropertyChanged("PostId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZoombuM1.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Create", ReplyAction="http://tempuri.org/IService1/CreateResponse")]
        ZoombuM1.ServiceReference1.User Create(ZoombuM1.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Create", ReplyAction="http://tempuri.org/IService1/CreateResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User> CreateAsync(ZoombuM1.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByEmailAndPass", ReplyAction="http://tempuri.org/IService1/GetUserByEmailAndPassResponse")]
        ZoombuM1.ServiceReference1.User GetUserByEmailAndPass(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByEmailAndPass", ReplyAction="http://tempuri.org/IService1/GetUserByEmailAndPassResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User> GetUserByEmailAndPassAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        ZoombuM1.ServiceReference1.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByName", ReplyAction="http://tempuri.org/IService1/GetUserByNameResponse")]
        ZoombuM1.ServiceReference1.User[] GetUserByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByName", ReplyAction="http://tempuri.org/IService1/GetUserByNameResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User[]> GetUserByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUser", ReplyAction="http://tempuri.org/IService1/GetAllUserResponse")]
        ZoombuM1.ServiceReference1.User[] GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUser", ReplyAction="http://tempuri.org/IService1/GetAllUserResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User[]> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserToGroup", ReplyAction="http://tempuri.org/IService1/AddUserToGroupResponse")]
        int AddUserToGroup(int idUser, int idGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserToGroup", ReplyAction="http://tempuri.org/IService1/AddUserToGroupResponse")]
        System.Threading.Tasks.Task<int> AddUserToGroupAsync(int idUser, int idGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveUserFromGroup", ReplyAction="http://tempuri.org/IService1/RemoveUserFromGroupResponse")]
        int RemoveUserFromGroup(int idUser, int idGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveUserFromGroup", ReplyAction="http://tempuri.org/IService1/RemoveUserFromGroupResponse")]
        System.Threading.Tasks.Task<int> RemoveUserFromGroupAsync(int idUser, int idGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFollow", ReplyAction="http://tempuri.org/IService1/AddFollowResponse")]
        int AddFollow(int idUser, int idUserDestinataire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFollow", ReplyAction="http://tempuri.org/IService1/AddFollowResponse")]
        System.Threading.Tasks.Task<int> AddFollowAsync(int idUser, int idUserDestinataire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFollow", ReplyAction="http://tempuri.org/IService1/RemoveFollowResponse")]
        int RemoveFollow(int idUser, int idUserDestinataire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFollow", ReplyAction="http://tempuri.org/IService1/RemoveFollowResponse")]
        System.Threading.Tasks.Task<int> RemoveFollowAsync(int idUser, int idUserDestinataire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupById", ReplyAction="http://tempuri.org/IService1/GetGroupByIdResponse")]
        ZoombuM1.ServiceReference1.Group GetGroupById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupById", ReplyAction="http://tempuri.org/IService1/GetGroupByIdResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Group> GetGroupByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGroup", ReplyAction="http://tempuri.org/IService1/DeleteGroupResponse")]
        int DeleteGroup(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGroup", ReplyAction="http://tempuri.org/IService1/DeleteGroupResponse")]
        System.Threading.Tasks.Task<int> DeleteGroupAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateGroup", ReplyAction="http://tempuri.org/IService1/CreateGroupResponse")]
        int CreateGroup(ZoombuM1.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateGroup", ReplyAction="http://tempuri.org/IService1/CreateGroupResponse")]
        System.Threading.Tasks.Task<int> CreateGroupAsync(ZoombuM1.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePost", ReplyAction="http://tempuri.org/IService1/CreatePostResponse")]
        ZoombuM1.ServiceReference1.Post CreatePost(ZoombuM1.ServiceReference1.Post post, int idUser, int idGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePost", ReplyAction="http://tempuri.org/IService1/CreatePostResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post> CreatePostAsync(ZoombuM1.ServiceReference1.Post post, int idUser, int idGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostByGroup", ReplyAction="http://tempuri.org/IService1/GetPostByGroupResponse")]
        ZoombuM1.ServiceReference1.Post[] GetPostByGroup(ZoombuM1.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostByGroup", ReplyAction="http://tempuri.org/IService1/GetPostByGroupResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post[]> GetPostByGroupAsync(ZoombuM1.ServiceReference1.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostById", ReplyAction="http://tempuri.org/IService1/GetPostByIdResponse")]
        ZoombuM1.ServiceReference1.Post GetPostById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostById", ReplyAction="http://tempuri.org/IService1/GetPostByIdResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post> GetPostByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostByName", ReplyAction="http://tempuri.org/IService1/GetPostByNameResponse")]
        ZoombuM1.ServiceReference1.Post[] GetPostByName(string name, ZoombuM1.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostByName", ReplyAction="http://tempuri.org/IService1/GetPostByNameResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post[]> GetPostByNameAsync(string name, ZoombuM1.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePost", ReplyAction="http://tempuri.org/IService1/DeletePostResponse")]
        int DeletePost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePost", ReplyAction="http://tempuri.org/IService1/DeletePostResponse")]
        System.Threading.Tasks.Task<int> DeletePostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostFollow", ReplyAction="http://tempuri.org/IService1/GetPostFollowResponse")]
        ZoombuM1.ServiceReference1.Post[] GetPostFollow(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPostFollow", ReplyAction="http://tempuri.org/IService1/GetPostFollowResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post[]> GetPostFollowAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPictureToAPost", ReplyAction="http://tempuri.org/IService1/AddPictureToAPostResponse")]
        int AddPictureToAPost(ZoombuM1.ServiceReference1.Post post, string pathPicture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPictureToAPost", ReplyAction="http://tempuri.org/IService1/AddPictureToAPostResponse")]
        System.Threading.Tasks.Task<int> AddPictureToAPostAsync(ZoombuM1.ServiceReference1.Post post, string pathPicture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLike", ReplyAction="http://tempuri.org/IService1/CreateLikeResponse")]
        int CreateLike(ZoombuM1.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLike", ReplyAction="http://tempuri.org/IService1/CreateLikeResponse")]
        System.Threading.Tasks.Task<int> CreateLikeAsync(ZoombuM1.ServiceReference1.Like like);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLike", ReplyAction="http://tempuri.org/IService1/DeleteLikeResponse")]
        int DeleteLike(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLike", ReplyAction="http://tempuri.org/IService1/DeleteLikeResponse")]
        System.Threading.Tasks.Task<int> DeleteLikeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLikeById", ReplyAction="http://tempuri.org/IService1/GetLikeByIdResponse")]
        ZoombuM1.ServiceReference1.Like GetLikeById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLikeById", ReplyAction="http://tempuri.org/IService1/GetLikeByIdResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Like> GetLikeByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateComment", ReplyAction="http://tempuri.org/IService1/CreateCommentResponse")]
        int CreateComment(ZoombuM1.ServiceReference1.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateComment", ReplyAction="http://tempuri.org/IService1/CreateCommentResponse")]
        System.Threading.Tasks.Task<int> CreateCommentAsync(ZoombuM1.ServiceReference1.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteComment", ReplyAction="http://tempuri.org/IService1/DeleteCommentResponse")]
        int DeleteComment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteComment", ReplyAction="http://tempuri.org/IService1/DeleteCommentResponse")]
        System.Threading.Tasks.Task<int> DeleteCommentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCommentById", ReplyAction="http://tempuri.org/IService1/GetCommentByIdResponse")]
        ZoombuM1.ServiceReference1.Comment GetCommentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCommentById", ReplyAction="http://tempuri.org/IService1/GetCommentByIdResponse")]
        System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Comment> GetCommentByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ZoombuM1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ZoombuM1.ServiceReference1.IService1>, ZoombuM1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZoombuM1.ServiceReference1.User Create(ZoombuM1.ServiceReference1.User user) {
            return base.Channel.Create(user);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User> CreateAsync(ZoombuM1.ServiceReference1.User user) {
            return base.Channel.CreateAsync(user);
        }
        
        public ZoombuM1.ServiceReference1.User GetUserByEmailAndPass(string email, string pass) {
            return base.Channel.GetUserByEmailAndPass(email, pass);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User> GetUserByEmailAndPassAsync(string email, string pass) {
            return base.Channel.GetUserByEmailAndPassAsync(email, pass);
        }
        
        public ZoombuM1.ServiceReference1.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public ZoombuM1.ServiceReference1.User[] GetUserByName(string name) {
            return base.Channel.GetUserByName(name);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User[]> GetUserByNameAsync(string name) {
            return base.Channel.GetUserByNameAsync(name);
        }
        
        public ZoombuM1.ServiceReference1.User[] GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.User[]> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
        
        public int AddUserToGroup(int idUser, int idGroup) {
            return base.Channel.AddUserToGroup(idUser, idGroup);
        }
        
        public System.Threading.Tasks.Task<int> AddUserToGroupAsync(int idUser, int idGroup) {
            return base.Channel.AddUserToGroupAsync(idUser, idGroup);
        }
        
        public int RemoveUserFromGroup(int idUser, int idGroup) {
            return base.Channel.RemoveUserFromGroup(idUser, idGroup);
        }
        
        public System.Threading.Tasks.Task<int> RemoveUserFromGroupAsync(int idUser, int idGroup) {
            return base.Channel.RemoveUserFromGroupAsync(idUser, idGroup);
        }
        
        public int AddFollow(int idUser, int idUserDestinataire) {
            return base.Channel.AddFollow(idUser, idUserDestinataire);
        }
        
        public System.Threading.Tasks.Task<int> AddFollowAsync(int idUser, int idUserDestinataire) {
            return base.Channel.AddFollowAsync(idUser, idUserDestinataire);
        }
        
        public int RemoveFollow(int idUser, int idUserDestinataire) {
            return base.Channel.RemoveFollow(idUser, idUserDestinataire);
        }
        
        public System.Threading.Tasks.Task<int> RemoveFollowAsync(int idUser, int idUserDestinataire) {
            return base.Channel.RemoveFollowAsync(idUser, idUserDestinataire);
        }
        
        public ZoombuM1.ServiceReference1.Group GetGroupById(int id) {
            return base.Channel.GetGroupById(id);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Group> GetGroupByIdAsync(int id) {
            return base.Channel.GetGroupByIdAsync(id);
        }
        
        public int DeleteGroup(int id) {
            return base.Channel.DeleteGroup(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteGroupAsync(int id) {
            return base.Channel.DeleteGroupAsync(id);
        }
        
        public int CreateGroup(ZoombuM1.ServiceReference1.Group group) {
            return base.Channel.CreateGroup(group);
        }
        
        public System.Threading.Tasks.Task<int> CreateGroupAsync(ZoombuM1.ServiceReference1.Group group) {
            return base.Channel.CreateGroupAsync(group);
        }
        
        public ZoombuM1.ServiceReference1.Post CreatePost(ZoombuM1.ServiceReference1.Post post, int idUser, int idGroup) {
            return base.Channel.CreatePost(post, idUser, idGroup);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post> CreatePostAsync(ZoombuM1.ServiceReference1.Post post, int idUser, int idGroup) {
            return base.Channel.CreatePostAsync(post, idUser, idGroup);
        }
        
        public ZoombuM1.ServiceReference1.Post[] GetPostByGroup(ZoombuM1.ServiceReference1.Group group) {
            return base.Channel.GetPostByGroup(group);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post[]> GetPostByGroupAsync(ZoombuM1.ServiceReference1.Group group) {
            return base.Channel.GetPostByGroupAsync(group);
        }
        
        public ZoombuM1.ServiceReference1.Post GetPostById(int id) {
            return base.Channel.GetPostById(id);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post> GetPostByIdAsync(int id) {
            return base.Channel.GetPostByIdAsync(id);
        }
        
        public ZoombuM1.ServiceReference1.Post[] GetPostByName(string name, ZoombuM1.ServiceReference1.User user) {
            return base.Channel.GetPostByName(name, user);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post[]> GetPostByNameAsync(string name, ZoombuM1.ServiceReference1.User user) {
            return base.Channel.GetPostByNameAsync(name, user);
        }
        
        public int DeletePost(int id) {
            return base.Channel.DeletePost(id);
        }
        
        public System.Threading.Tasks.Task<int> DeletePostAsync(int id) {
            return base.Channel.DeletePostAsync(id);
        }
        
        public ZoombuM1.ServiceReference1.Post[] GetPostFollow(int id) {
            return base.Channel.GetPostFollow(id);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Post[]> GetPostFollowAsync(int id) {
            return base.Channel.GetPostFollowAsync(id);
        }
        
        public int AddPictureToAPost(ZoombuM1.ServiceReference1.Post post, string pathPicture) {
            return base.Channel.AddPictureToAPost(post, pathPicture);
        }
        
        public System.Threading.Tasks.Task<int> AddPictureToAPostAsync(ZoombuM1.ServiceReference1.Post post, string pathPicture) {
            return base.Channel.AddPictureToAPostAsync(post, pathPicture);
        }
        
        public int CreateLike(ZoombuM1.ServiceReference1.Like like) {
            return base.Channel.CreateLike(like);
        }
        
        public System.Threading.Tasks.Task<int> CreateLikeAsync(ZoombuM1.ServiceReference1.Like like) {
            return base.Channel.CreateLikeAsync(like);
        }
        
        public int DeleteLike(int id) {
            return base.Channel.DeleteLike(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteLikeAsync(int id) {
            return base.Channel.DeleteLikeAsync(id);
        }
        
        public ZoombuM1.ServiceReference1.Like GetLikeById(int id) {
            return base.Channel.GetLikeById(id);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Like> GetLikeByIdAsync(int id) {
            return base.Channel.GetLikeByIdAsync(id);
        }
        
        public int CreateComment(ZoombuM1.ServiceReference1.Comment comment) {
            return base.Channel.CreateComment(comment);
        }
        
        public System.Threading.Tasks.Task<int> CreateCommentAsync(ZoombuM1.ServiceReference1.Comment comment) {
            return base.Channel.CreateCommentAsync(comment);
        }
        
        public int DeleteComment(int id) {
            return base.Channel.DeleteComment(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCommentAsync(int id) {
            return base.Channel.DeleteCommentAsync(id);
        }
        
        public ZoombuM1.ServiceReference1.Comment GetCommentById(int id) {
            return base.Channel.GetCommentById(id);
        }
        
        public System.Threading.Tasks.Task<ZoombuM1.ServiceReference1.Comment> GetCommentByIdAsync(int id) {
            return base.Channel.GetCommentByIdAsync(id);
        }
    }
}
